### ISSUE TITLE
Fix pcap error

### ISSUE THREAD

**Issue by ecaron** [ecaron/smart-nightlight-manager#4]
First mentioned on https://github.com/hortinstein/node-dash-button/issues/6
Figure out how to reproduce it, and then stop it.

**Comment by ecaron** [comment]
Here's the error I'm getting:

```
node_pcap: EthernetFrame() - Don't know how to decode ethertype 34824
node_pcap: EthernetFrame() - Don't know how to decode ethertype 34824
node_pcap: EthernetFrame() - Don't know how to decode ethertype 34824
node_pcap: EthernetFrame() - Don't know how to decode ethertype 34824
node_pcap: EthernetFrame() - Don't know how to decode ethertype 34824
node_pcap: EthernetFrame() - Don't know how to decode ethertype 34824
node_pcap: EthernetFrame() - Don't know how to decode ethertype 34824
```

Typically shows up when the script runs overnight.

**Comment by ecaron** [comment]
Considering this fixed by https://github.com/hortinstein/node-dash-button/issues/6 and https://github.com/mranney/node_pcap/pull/195

**Comment by LondonSi72** [comment]
Hi - sorry for the real newbie question, but I'm interested in implementing your fix for the logging issue in node_pcap.  I'm using the node-dash-button and node-red-contrib-amazondash packages for a dash button home automation implementation using a Raspberry Pi Zero W. I have everything working but I get excessive messages from node_pcap regarding ethertype 34924 and after a few hours the system crashes. (I found the wifi in Pi Zero w works, whereas the wifi on the Pi 3 doesn't see the packets from the dash button.  I don't want to connect to the router directly via ethernet cable if I can avoid it.)  I found your fix for silencing the logging in pcap, but I can't figure out how to implement it.  I installed libpcap via apt-get, as instructed in the node-dash-button readme.md, but I suspect I need to re-install it via github and issue a git command to get your changes.  Can you help me with  what I need to do to implement this properly?

Many thanks
Si
